In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

In [3]:
import nltk

In [4]:
import nltk.corpus

In [5]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\alpino.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\biocreative_ppi.zip.
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\brown.zip.
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data] 

True

In [6]:
AI='This video will provide you with a comprehensive and detailed knowledge of Natural Language Processing,popularly known as NLP. You will also learn about the different steps involved in processing the human language like Tokenization, Stemming, Lemmatization and more. Python, NLTK, & Jupyter Notebook are used to demonstrate the concepts'

In [7]:
type(AI)

str

In [8]:
from nltk.tokenize import word_tokenize

In [9]:
AI_Token=word_tokenize(AI)

In [10]:
print(AI_Token)

['This', 'video', 'will', 'provide', 'you', 'with', 'a', 'comprehensive', 'and', 'detailed', 'knowledge', 'of', 'Natural', 'Language', 'Processing', ',', 'popularly', 'known', 'as', 'NLP', '.', 'You', 'will', 'also', 'learn', 'about', 'the', 'different', 'steps', 'involved', 'in', 'processing', 'the', 'human', 'language', 'like', 'Tokenization', ',', 'Stemming', ',', 'Lemmatization', 'and', 'more', '.', 'Python', ',', 'NLTK', ',', '&', 'Jupyter', 'Notebook', 'are', 'used', 'to', 'demonstrate', 'the', 'concepts']


In [11]:
len(AI_Token)

57

In [12]:
from nltk.probability import FreqDist

In [19]:
fdist=FreqDist()
for word in AI_Token:
    fdist[word]+=1
    fdist

In [22]:
fdist['the']

3

In [23]:
from nltk.tokenize import blankline_tokenize
AI_blankline=blankline_tokenize(AI)
AI_blankline

['This video will provide you with a comprehensive and detailed knowledge of Natural Language Processing,popularly known as NLP. You will also learn about the different steps involved in processing the human language like Tokenization, Stemming, Lemmatization and more. Python, NLTK, & Jupyter Notebook are used to demonstrate the concepts']

In [24]:
from nltk.util import bigrams,ngrams,trigrams

In [26]:
print(list(bigrams(AI_Token)))

[('This', 'video'), ('video', 'will'), ('will', 'provide'), ('provide', 'you'), ('you', 'with'), ('with', 'a'), ('a', 'comprehensive'), ('comprehensive', 'and'), ('and', 'detailed'), ('detailed', 'knowledge'), ('knowledge', 'of'), ('of', 'Natural'), ('Natural', 'Language'), ('Language', 'Processing'), ('Processing', ','), (',', 'popularly'), ('popularly', 'known'), ('known', 'as'), ('as', 'NLP'), ('NLP', '.'), ('.', 'You'), ('You', 'will'), ('will', 'also'), ('also', 'learn'), ('learn', 'about'), ('about', 'the'), ('the', 'different'), ('different', 'steps'), ('steps', 'involved'), ('involved', 'in'), ('in', 'processing'), ('processing', 'the'), ('the', 'human'), ('human', 'language'), ('language', 'like'), ('like', 'Tokenization'), ('Tokenization', ','), (',', 'Stemming'), ('Stemming', ','), (',', 'Lemmatization'), ('Lemmatization', 'and'), ('and', 'more'), ('more', '.'), ('.', 'Python'), ('Python', ','), (',', 'NLTK'), ('NLTK', ','), (',', '&'), ('&', 'Jupyter'), ('Jupyter', 'Noteboo

In [27]:
print(list(trigrams(AI_Token)))

[('This', 'video', 'will'), ('video', 'will', 'provide'), ('will', 'provide', 'you'), ('provide', 'you', 'with'), ('you', 'with', 'a'), ('with', 'a', 'comprehensive'), ('a', 'comprehensive', 'and'), ('comprehensive', 'and', 'detailed'), ('and', 'detailed', 'knowledge'), ('detailed', 'knowledge', 'of'), ('knowledge', 'of', 'Natural'), ('of', 'Natural', 'Language'), ('Natural', 'Language', 'Processing'), ('Language', 'Processing', ','), ('Processing', ',', 'popularly'), (',', 'popularly', 'known'), ('popularly', 'known', 'as'), ('known', 'as', 'NLP'), ('as', 'NLP', '.'), ('NLP', '.', 'You'), ('.', 'You', 'will'), ('You', 'will', 'also'), ('will', 'also', 'learn'), ('also', 'learn', 'about'), ('learn', 'about', 'the'), ('about', 'the', 'different'), ('the', 'different', 'steps'), ('different', 'steps', 'involved'), ('steps', 'involved', 'in'), ('involved', 'in', 'processing'), ('in', 'processing', 'the'), ('processing', 'the', 'human'), ('the', 'human', 'language'), ('human', 'language', 

In [29]:
from nltk.stem import PorterStemmer  # Stemming

In [30]:
stemmer=PorterStemmer()

In [31]:
stemmer.stem('concepts')

'concept'

In [33]:
PorterStemmer().stem('Jumping')

'jump'

In [34]:
from nltk.stem import WordNetLemmatizer # Lemmatization

In [35]:
WordNetLemmatizer().lemmatize('Jumping')

'Jumping'

In [36]:
WordNetLemmatizer().lemmatize('Rohith')

'Rohith'

In [37]:
from nltk.corpus import stopwords

In [39]:
stopwords.words('English')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [47]:
## Applying lemattozation using for loop:


from nltk.stem import WordNetLemmatizer

lem=WordNetLemmatizer()


def apply_stem(sentence):
    a=[]
    sentence=sentence.split()
    
    for word in sentence:
        word=lem.lemmatize(word)
        a.append(word)
        
    corpus_join=" ".join(a)
    
    return corpus_join


In [50]:
a=apply_stem('i likes  avenger but not a great movie for grown ups')
print(a)

i like avenger but not a great movie for grown ups


In [44]:
from nltk.stem import WordNetLemmatizer
lem=WordNetLemmatizer()


def apply_stem(sentence):
    
    clean_list=[]
    sentence=sentence.split()
    for word in sentence:
        word=lem.lemmatize(word)
        clean_list.append(word)
        
    clean_sentence=" ".join(clean_list)
    
    return clean_sentence

spel_1 = "i like avenger but not a Great Movie for grown-ups"
spel_2 = "i likes  avenger but not a great movie for grown ups"

clean_spel_1 = apply_stem(spel_1)
clean_spel_2 = apply_stem(spel_2)

print (clean_spel_1)
print (clean_spel_2)

i like avenger but not a Great Movie for grown-ups
i like avenger but not a great movie for grown ups


In [51]:
# Countvectorizer and TFIDFVectorizer

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

In [53]:
corpus=['My name is Rohith',
       'This is the first document',
        'And this is the third one',
        'Is this the first document?']

In [54]:
vectorizer=CountVectorizer()

In [55]:
X=vectorizer.fit_transform(corpus)

In [57]:
(X.toarray())

array([[0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [60]:
print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'my', 'name', 'one', 'rohith', 'the', 'third', 'this']


In [61]:
 vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [62]:
 X2 = vectorizer2.fit_transform(corpus)

In [64]:
print(X2.toarray())

[[0 0 1 0 0 1 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 1 0 0 1 0]
 [1 0 0 1 0 0 0 0 1 1 1 0]
 [0 1 0 0 1 0 0 1 0 0 0 1]]


In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [67]:
corpus=['My name is Rohith',
       'This is the first document',
        'And this is the third one',
        'Is this the first document?']

In [69]:
vectorizer1=TfidfVectorizer()

In [70]:
X3=vectorizer1.fit_transform(corpus)

In [72]:
print(X3.toarray())

[[0.         0.         0.         0.28847675 0.55280532 0.55280532
  0.         0.55280532 0.         0.         0.        ]
 [0.         0.51646957 0.51646957 0.34184591 0.         0.
  0.         0.         0.41812662 0.         0.41812662]
 [0.4946412  0.         0.         0.2581243  0.         0.
  0.4946412  0.         0.31572307 0.4946412  0.31572307]
 [0.         0.51646957 0.51646957 0.34184591 0.         0.
  0.         0.         0.41812662 0.         0.41812662]]


In [73]:
print(vectorizer1.get_feature_names())

['and', 'document', 'first', 'is', 'my', 'name', 'one', 'rohith', 'the', 'third', 'this']
